### ISSUE TITLE
Deprecate ci-docker-bases, stop updating on October 1, 2022

### ISSUE THREAD

**Issue by jwhitlock** [mozilla/ci-docker-bases#322]
The maintainers of this project are no longer with Mozilla, and Github searches shows the images are only used by Mozilla projects. After some discussion (see [Decision brief: Transition mozilla/ci-docker-bases project](https://docs.google.com/document/d/1xW6SANLXmh4pPDeyU7Zenim-XXteXzNyy1tYeWIN6pg/edit#)), we agreed to deprecate the project and stop updating images on October 1, 2022

Relying projects should use other images, such as the [Pre-Built CircleCI Docker Images](https://circleci.com/docs/2.0/circleci-images/).

##  mozilla/cidockerbases:docker

`mozilla/cidockerbases:docker` was added August 2018, and was used by [15 repositories](https://github.com/search?q=filename%3Aconfig.yml+path%3A%2F.circleci+%22image%3A+mozilla%2Fcidockerbases%3Adocker%22&type=code) in February 2022:
* [ ] [mozilla-releng/buildhub2](https://github.com/mozilla-releng/buildhub2) - [Issue #953](https://github.com/mozilla-releng/buildhub2/issues/953)
* [x] [mozilla-services/antenna](https://github.com/mozilla-services/antenna) - [PR 783](https://github.com/mozilla-services/antenna/pull/783)
* [ ] [mozilla-services/lua_sandbox_extensions](https://github.com/mozilla-services/lua_sandbox_extensions) - [Issue #537](https://github.com/mozilla-services/lua_sandbox_extensions/issues/537)
* [x] [mozilla-services/merino](https://github.com/mozilla-services/merino) - [PR 411](https://github.com/mozilla-services/merino/pull/411)
* [x] [mozilla-services/minidump-stackwalk](https://github.com/mozilla-services/minidump-stackwalk) (*archived*)
* [x] [mozilla-services/socorro](https://github.com/mozilla-services/socorro) - [PR 6028](https://github.com/mozilla-services/socorro/pull/6028)
* [x] [mozilla-services/socorro-submitter](https://github.com/mozilla-services/socorro-submitter) - [PR 37](https://github.com/mozilla-services/socorro-submitter/pull/37)
* [x] [mozilla-services/tecken](https://github.com/mozilla-services/tecken) - [PR 2519](https://github.com/mozilla-services/tecken/pull/2519)
* [x] [mozilla/ci-docker-bases](https://github.com/mozilla/ci-docker-bases) - [PR 410](https://github.com/mozilla/ci-docker-bases/pull/410)
* [x] [mozilla/classify-client](https://github.com/mozilla/classify-client) - [PR 125](https://github.com/mozilla/classify-client/pull/125)
* [x] [mozilla/docker-test-mozilla-django-oidc](https://github.com/mozilla/docker-test-mozilla-django-oidc) - [PR 35](https://github.com/mozilla/docker-test-mozilla-django-oidc/pull/35)
* [ ] [mozilla/firefox-public-data-report-etl](https://github.com/mozilla/firefox-public-data-report-etl) - [Issue #9](https://github.com/mozilla/firefox-public-data-report-etl/issues/9)
* [x] [mozilla/ichnaea](https://github.com/mozilla/ichnaea) - [PR 1804](https://github.com/mozilla/ichnaea/pull/1804)
* [ ] [mozilla/normandy](https://github.com/mozilla/normandy) - [Issue #2338](https://github.com/mozilla/normandy/issues/2338)
* [ ] [mozilla-it/pocket-proxy-rs](https://github.com/mozilla-it/pocket-proxy-rs) - [Issue #10](https://github.com/mozilla-it/pocket-proxy-rs/issues/10)

##  mozilla/cidockerbases:firefox

`mozilla/cidockerbases:firefox` was added August 2018, and is used by [no repositories](https://github.com/search?q=filename%3Aconfig.yml+path%3A%2F.circleci+%22image%3A+mozilla%2Fcidockerbases%3Afirefox%22&type=code). It was removed from build automation on September 2, 2022.

##  mozilla/cidockerbases:therapist

`mozilla/cidockerbases:therapist` was added April 2019 and is used by [3 repositories](https://github.com/search?q=filename%3Aconfig.yml+path%3A%2F.circleci+%22image%3A+mozilla%2Fcidockerbases%3Atherapist%22&type=code):
* [x] [mozilla-extensions/normandy-devtools](https://github.com/mozilla-extensions/normandy-devtools) (*archived*)
* [ ] [mozilla/normandy](https://github.com/mozilla/normandy) - [Issue #2338](https://github.com/mozilla/normandy/issues/2338)
* [x] [mozilla/xpihub](https://github.com/mozilla/xpihub) (*archived*)

##  mozilla/cidockerbases:rust

`mozilla/cidockerbases:rust` was added June 2019 and is used by [4 repositories](https://github.com/search?q=filename%3Aconfig.yml+path%3A%2F.circleci+%22image%3A+mozilla%2Fcidockerbases%3Arust%22&type=code):
* [x] [mozilla-services/common-rs](https://github.com/mozilla-services/common-rs) - [PR 46](https://github.com/mozilla-services/common-rs/pull/46)
* [x] [mozilla/classify-client](https://github.com/mozilla/classify-client) - [PR 125](https://github.com/mozilla/classify-client/pull/125)
* [x] [mozilla-services/merino](https://github.com/mozilla-services/merino) - [PR 411](https://github.com/mozilla-services/merino/pull/411)
* [x] [mozilla-services/remote-settings-client](https://github.com/mozilla-services/remote-settings-client) - [PR 207](https://github.com/mozilla-services/remote-settings-client/pull/207)
* [ ] [mozilla-it/pocket-proxy-rs](https://github.com/mozilla-it/pocket-proxy-rs) - [Issue #10](https://github.com/mozilla-it/pocket-proxy-rs/issues/10)
* [x] [mozilla/Fx_Usage_Report](https://github.com/mozilla/Fx_Usage_Report) (*archived*)

**Comment by jwhitlock** [comment]
Archiving this repo. The identified projects continue using these images, but also have no activity since April 15th.
